import argparse
from pathlib import Path

import imageio.v2 as imageio
import mujoco
import mujoco.viewer
import numpy as np


BASE_DIR = Path(__file__).resolve().parent
XML_PATH = BASE_DIR / "mujoco_menagerie" / "trossen_vx300s" / "vx300s.xml"


def parse_args():
    parser = argparse.ArgumentParser(description="Task 2 - Replay wrist trajectory on VX300s with IK")
    parser.add_argument(
        "--trajectory-csv",
        default=str(BASE_DIR / "outputs" / "task2" / "wrist_trajectory.csv"),
        help="Wrist trajectory CSV generated by task2_pipeline.py",
    )
    parser.add_argument(
        "--output-video",
        default=str(BASE_DIR / "outputs" / "task2_vx300s_replay.mp4"),
        help="Output replay video path",
    )
    parser.add_argument("--save-video", action="store_true", help="Enable video recording")
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--video-width", type=int, default=640)
    parser.add_argument("--video-height", type=int, default=480)
    parser.add_argument("--ik-iters", type=int, default=25)
    parser.add_argument("--ik-tol", type=float, default=2e-3)
    parser.add_argument("--return-steps", type=int, default=24, help="Number of final steps to return to home pose")
    parser.add_argument(
        "--mode",
        choices=["transfer", "follow"],
        default="transfer",
        help="transfer: right-left transfer behavior, follow: direct wrist tracking",
    )
    parser.add_argument("--smooth-window", type=int, default=7, help="Trajectory smoothing window")
    parser.add_argument("--wrist-angle-gain", type=float, default=1.1, help="Pour tilt gain")
    parser.add_argument("--wrist-rotate-gain", type=float, default=0.9, help="Wrist rotate gain")
    parser.add_argument("--side-scale", type=float, default=0.18, help="Right-left movement amplitude")
    parser.add_argument("--lift-height", type=float, default=0.08, help="Lift height during transfer")
    return parser.parse_args()


def load_wrist_csv(path: str) -> np.ndarray:
    arr = np.loadtxt(path, delimiter=",", skiprows=1)
    if arr.ndim == 1:
        arr = arr[None, :]
    return arr


def smooth_1d(x: np.ndarray, window: int) -> np.ndarray:
    if window <= 1 or x.shape[0] < window:
        return x.copy()
    kernel = np.ones(window, dtype=np.float64) / float(window)
    pad = window // 2
    xp = np.pad(x, (pad, pad), mode="edge")
    return np.convolve(xp, kernel, mode="valid")


def smooth_columns(arr: np.ndarray, window: int) -> np.ndarray:
    out = arr.copy()
    for c in range(arr.shape[1]):
        out[:, c] = smooth_1d(arr[:, c], window)
    return out


def map_wrist_to_targets(wrist_xyz: np.ndarray, base_target: np.ndarray, smooth_window: int) -> np.ndarray:
    """
    Map normalized wrist coordinates to robot workspace targets.
    This uses a simple affine mapping; scale factors may need tuning per video.
    """
    wrist_xyz = smooth_columns(wrist_xyz, smooth_window)
    x = wrist_xyz[:, 0]
    y = wrist_xyz[:, 1]
    z = wrist_xyz[:, 2]

    x0, y0, z0 = x[0], y[0], z[0]
    dx = (x - x0) * 0.18
    dy = (y - y0) * 0.18
    dz = (z - z0) * 0.15

    targets = np.zeros((wrist_xyz.shape[0], 3), dtype=np.float64)
    targets[:, 0] = base_target[0] + dx
    targets[:, 1] = base_target[1] - dy
    targets[:, 2] = base_target[2] - dz
    return targets


def build_transfer_targets_and_gripper(
    wrist_xyz: np.ndarray,
    base_target: np.ndarray,
    smooth_window: int,
    side_scale: float,
    lift_height: float,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Transfer behavior:
    - pick from right -> place to left
    - pick from left -> place to right
    - keep wrist rotation fixed
    """
    w = smooth_columns(wrist_xyz, smooth_window)
    x = w[:, 0]
    y = w[:, 1]

    # Normalize x and map it to right-left axis
    x_center = float(np.median(x))
    x_span = float(np.max(x) - np.min(x))
    if x_span < 1e-6:
        x_span = 1.0
    x_norm = np.clip((x - x_center) / (0.5 * x_span), -1.0, 1.0)

    # Light y-tracking; main motion is right-left transfer
    y0 = y[0]
    y_delta = (y - y0) * 0.04

    targets = np.zeros((w.shape[0], 3), dtype=np.float64)
    targets[:, 0] = base_target[0] + y_delta
    targets[:, 1] = base_target[1] + side_scale * x_norm

    # Lower at extremes, higher during transfer
    mid_factor = 1.0 - np.abs(x_norm)  # merkezde 1, kenarda 0
    targets[:, 2] = base_target[2] + lift_height * mid_factor

    # Gripper state machine: close on right, open on left
    gripper = np.zeros(w.shape[0], dtype=np.float64)
    grip_closed = 0.024
    grip_open = 0.048
    state_closed = False
    for i in range(w.shape[0]):
        if x_norm[i] > 0.65:
            state_closed = True   # pick from right
        elif x_norm[i] < -0.65:
            state_closed = False  # place to left
        gripper[i] = grip_closed if state_closed else grip_open

    return targets, gripper


def compute_wrist_signals(traj: np.ndarray, smooth_window: int) -> tuple[np.ndarray, np.ndarray]:
    """
    Extract wrist orientation signals if extra landmarks exist in the CSV:
    - wrist_rotate: based on index_mcp -> pinky_mcp axis
    - wrist_angle: based on wrist -> middle_mcp vector (pour tilt)
    Returns zeros for legacy 4-column CSV format.
    """
    n = traj.shape[0]
    if traj.shape[1] < 13:
        return np.zeros(n, dtype=np.float64), np.zeros(n, dtype=np.float64)

    index_xyz = traj[:, 4:7].astype(np.float64)
    middle_xyz = traj[:, 7:10].astype(np.float64)
    pinky_xyz = traj[:, 10:13].astype(np.float64)
    wrist_xyz = traj[:, 1:4].astype(np.float64)

    index_xyz = smooth_columns(index_xyz, smooth_window)
    middle_xyz = smooth_columns(middle_xyz, smooth_window)
    pinky_xyz = smooth_columns(pinky_xyz, smooth_window)
    wrist_xyz = smooth_columns(wrist_xyz, smooth_window)

    hand_span = index_xyz - pinky_xyz
    yaw = np.arctan2(hand_span[:, 1], hand_span[:, 0])
    yaw = yaw - yaw[0]

    fore = middle_xyz - wrist_xyz
    tilt = np.arctan2(-fore[:, 2], np.sqrt(fore[:, 0] ** 2 + fore[:, 1] ** 2))
    tilt = tilt - tilt[0]
    return tilt, yaw


def clamp_to_joint_limits(model: mujoco.MjModel, data: mujoco.MjData, joint_ids: list[int]) -> None:
    for jid in joint_ids:
        qadr = model.jnt_qposadr[jid]
        jrange = model.jnt_range[jid]
        data.qpos[qadr] = np.clip(data.qpos[qadr], jrange[0], jrange[1])


def solve_ik_position(
    model: mujoco.MjModel,
    data: mujoco.MjData,
    site_id: int,
    target_pos: np.ndarray,
    joint_ids: list[int],
    max_iters: int = 25,
    tol: float = 2e-3,
    damping: float = 1e-4,
    step_size: float = 0.7,
) -> None:
    qadr = [model.jnt_qposadr[jid] for jid in joint_ids]
    nv_ids = [model.jnt_dofadr[jid] for jid in joint_ids]

    for _ in range(max_iters):
        mujoco.mj_forward(model, data)
        cur = data.site_xpos[site_id].copy()
        err = target_pos - cur
        if np.linalg.norm(err) < tol:
            break

        jacp = np.zeros((3, model.nv), dtype=np.float64)
        jacr = np.zeros((3, model.nv), dtype=np.float64)
        mujoco.mj_jacSite(model, data, jacp, jacr, site_id)
        j = jacp[:, nv_ids]  # selected joints only

        # Damped least squares: dq = J^T (J J^T + lI)^-1 e
        a = j @ j.T + damping * np.eye(3)
        dq = j.T @ np.linalg.solve(a, err)

        for i, qa in enumerate(qadr):
            data.qpos[qa] += step_size * dq[i]
        clamp_to_joint_limits(model, data, joint_ids)


def main():
    args = parse_args()
    traj = load_wrist_csv(args.trajectory_csv)
    wrist_xyz = traj[:, 1:4].astype(np.float64)

    model = mujoco.MjModel.from_xml_path(str(XML_PATH))
    data = mujoco.MjData(model)

    # Initialize from home keyframe
    if model.nkey > 0:
        data.qpos[:] = model.key_qpos[0]
        data.ctrl[:] = model.key_ctrl[0]
    mujoco.mj_forward(model, data)
    home_qpos = data.qpos.copy()

    site_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, "pinch")
    if site_id < 0:
        raise RuntimeError("Could not find 'pinch' site in VX300s model.")

    arm_joint_names = ["waist", "shoulder", "elbow", "forearm_roll", "wrist_angle", "wrist_rotate"]
    arm_joint_ids = [mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, n) for n in arm_joint_names]
    if any(j < 0 for j in arm_joint_ids):
        raise RuntimeError("Could not find expected VX300s arm joints.")
    home_ctrl = data.ctrl.copy()

    base_target = data.site_xpos[site_id].copy()
    smooth_window = max(1, args.smooth_window)
    if args.mode == "transfer":
        targets, gripper_sig = build_transfer_targets_and_gripper(
            wrist_xyz=wrist_xyz,
            base_target=base_target,
            smooth_window=smooth_window,
            side_scale=args.side_scale,
            lift_height=args.lift_height,
        )
        tilt_sig = np.zeros(targets.shape[0], dtype=np.float64)
        yaw_sig = np.zeros(targets.shape[0], dtype=np.float64)
    else:
        targets = map_wrist_to_targets(wrist_xyz, base_target, smooth_window=smooth_window)
        tilt_sig, yaw_sig = compute_wrist_signals(traj, smooth_window=smooth_window)
        gripper_sig = np.full(targets.shape[0], 0.035, dtype=np.float64)

    out_video = Path(args.output_video)
    out_video.parent.mkdir(parents=True, exist_ok=True)
    writer = imageio.get_writer(str(out_video), fps=args.fps) if args.save_video else None
    renderer = (
        mujoco.Renderer(model, height=args.video_height, width=args.video_width)
        if args.save_video
        else None
    )

    with mujoco.viewer.launch_passive(model, data) as viewer:
        for i in range(targets.shape[0]):
            solve_ik_position(
                model=model,
                data=data,
                site_id=site_id,
                target_pos=targets[i],
                joint_ids=arm_joint_ids,
                max_iters=args.ik_iters,
                tol=args.ik_tol,
            )

            # For position actuators, set ctrl to corresponding qpos
            for aidx, jid in enumerate(arm_joint_ids):
                data.ctrl[aidx] = data.qpos[model.jnt_qposadr[jid]]

            # Apply orientation signals from hand landmarks to wrist.
            if args.mode == "transfer":
                # Keep wrist orientation fixed in transfer mode.
                data.ctrl[4] = home_ctrl[4]
                data.ctrl[5] = home_ctrl[5]
            else:
                data.ctrl[4] = np.clip(
                    home_ctrl[4] + args.wrist_angle_gain * tilt_sig[i],
                    model.actuator_ctrlrange[4][0],
                    model.actuator_ctrlrange[4][1],
                )
                data.ctrl[5] = np.clip(
                    home_ctrl[5] + args.wrist_rotate_gain * yaw_sig[i],
                    model.actuator_ctrlrange[5][0],
                    model.actuator_ctrlrange[5][1],
                )

            # Open/close gripper signal
            data.ctrl[6] = np.clip(
                gripper_sig[i], model.actuator_ctrlrange[6][0], model.actuator_ctrlrange[6][1]
            )

            mujoco.mj_step(model, data)

            if writer is not None and renderer is not None:
                renderer.update_scene(data)
                frame = renderer.render()
                writer.append_data(frame)

            viewer.sync()

        # Return robot to home pose and home orientation at the end.
        if args.return_steps > 0:
            start_qpos = data.qpos.copy()
            start_ctrl = data.ctrl.copy()
            for t in range(args.return_steps):
                alpha = (t + 1) / float(args.return_steps)
                # Guaranteed return: directly interpolate qpos to home.
                data.qpos[:] = (1.0 - alpha) * start_qpos + alpha * home_qpos
                data.ctrl[:] = (1.0 - alpha) * start_ctrl + alpha * home_ctrl
                mujoco.mj_forward(model, data)
                mujoco.mj_step(model, data)
                if writer is not None and renderer is not None:
                    renderer.update_scene(data)
                    frame = renderer.render()
                    writer.append_data(frame)
                viewer.sync()

            # Hold home pose for a few frames.
            for _ in range(10):
                data.qpos[:] = home_qpos
                data.ctrl[:] = home_ctrl
                mujoco.mj_forward(model, data)
                mujoco.mj_step(model, data)
                if writer is not None and renderer is not None:
                    renderer.update_scene(data)
                    frame = renderer.render()
                    writer.append_data(frame)
                viewer.sync()

    if renderer is not None:
        renderer.close()
    if writer is not None:
        writer.close()
        print(f"Done: replay video saved -> {out_video}")
    else:
        print("Done: replay ran successfully (video recording disabled).")


if __name__ == "__main__":
    main()

